### ISSUE TITLE
Buttons not responding to taps on mobile (JS)

### ISSUE THREAD

**Issue by lucymhdavies** [lucymhdavies/egg-game#27]

**Comment by lucymhdavies** [comment]
Initial inspection seems like this was broken by https://github.com/hajimehoshi/ebiten/commit/099c7bd5c9c782aa4068680683f4353923680940

That being the case, either I'm interacting with the API wrong, or something has broken.

There are a few examples of Touch being used in the ebiten examples:

https://github.com/hajimehoshi/ebiten/tree/master/examples/2048
https://github.com/hajimehoshi/ebiten/tree/master/examples/paint
https://github.com/hajimehoshi/ebiten/tree/master/examples/drag <-- this being the simplest
https://github.com/hajimehoshi/ebiten/tree/master/examples/paint


So...

https://jsgo.io/github.com/hajimehoshi/ebiten/examples/drag works in desktop mode, also works in mobile mode but it was last compiled 11 months ago.

compiled again, and now it no longer works on mobile

Will raise a bug upstream

**Comment by hajimehoshi** [comment]
`drag` example worked with `gomobile install` with the latest Ebiten. Could you confirm this? Thanks!

**Comment by lucymhdavies** [comment]
I've not tried with gomobile. I only really use jsgo.io (at the moment).

The drag example doesn't seem to work there:
https://github.com/hajimehoshi/ebiten/issues/846

**Comment by hajimehoshi** [comment]
Oh sure. I think that's fixed :-)

**Comment by lucymhdavies** [comment]
Confirmed fixed :D

https://jsgo.io/github.com/lucymhdavies/egg-game
